In [13]:
import torch
import numpy as np
def print_val(x):
    print"Type" , type(x)
    print "Shape:", x.shape
    print "값:\n", x
    print("")
x= torch.rand(2,3,2)
print_val(x)

x=torch.randn(2,3)
print_val(x)

Type <class 'torch.Tensor'>
Shape: torch.Size([2, 3, 2])
값:
tensor([[[0.6161, 0.0598],
         [0.2130, 0.2925],
         [0.2040, 0.5524]],

        [[0.9053, 0.7947],
         [0.2955, 0.8605],
         [0.0192, 0.3830]]])

Type <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[ 0.4487,  0.0563, -1.0892],
        [ 0.2664,  0.1859, -0.1893]])



In [3]:
x= torch.randperm(4)
print_val(x)

Type <class 'torch.Tensor'>
Shape: torch.Size([4])
값:
tensor([0, 1, 2, 3])



In [4]:
x= torch.arange(0, 3, step=0.5)
print_val(x)

Type <class 'torch.Tensor'>
Shape: torch.Size([6])
값:
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])



In [6]:
print_val( torch.ones(3,4))
print_val( torch.zeros(3,4))

Type <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Type <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])



In [7]:
print_val( torch.Tensor(2,4))

Type <class 'torch.Tensor'>
Shape: torch.Size([2, 4])
값:
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 4.7785e-18, 0.0000e+00, 0.0000e+00]])



In [8]:
print_val( torch.Tensor([2,3]))
print_val( torch.Tensor([[2,3], [3,4]]))

Type <class 'torch.Tensor'>
Shape: torch.Size([2])
값:
tensor([2., 3.])

Type <class 'torch.Tensor'>
Shape: torch.Size([2, 2])
값:
tensor([[2., 3.],
        [3., 4.]])



In [9]:
x= torch.FloatTensor(2,3)
print_val(x)

x= x.type_as(torch.IntTensor())
print_val(x)

Type <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[-1.2587e+03,  4.5846e-41, -1.2588e+03],
        [ 4.5846e-41, -1.2586e+03,  4.5846e-41]])

Type <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[-1258,     0, -1258],
        [    0, -1258,     0]], dtype=torch.int32)



In [10]:
torch.FloatTensor(3,4,5).size()


torch.Size([3, 4, 5])

In [11]:
np_x=np.ndarray((2,3), dtype=int)
print_val(np_x)

x= torch.from_numpy(np_x)
print_val(x)

Type <type 'numpy.ndarray'>
Shape: (2, 3)
값:
[[              0               0               0]
 [              0               0 140518445023232]]

Type <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[              0,               0,               0],
        [              0,               0, 140518445023232]])

